server:
  http:
<<<<<<< HEAD
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
=======
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
    timeout: 1s
data:
  database:
    driver: mysql
<<<<<<< HEAD
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
=======
    source: root:123456@tcp(127.0.0.1:3306)/laomadj_customer?charset=utf8mb4&parseTime=True&loc=Local
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
