// Code generated by Wire. DO NOT EDIT.

<<<<<<< HEAD
//go:generate go run -mod=mod github.com/google/wire/cmd/wire
=======
//go:generate go run github.com/google/wire/cmd/wire
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer/internal/biz"
	"customer/internal/conf"
	"customer/internal/data"
	"customer/internal/server"
	"customer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

<<<<<<< HEAD
import (
	_ "go.uber.org/automaxprocs"
)

=======
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
<<<<<<< HEAD
	customerService := service.NewCustomerService()
=======
	customerData := data.NewCustomerData(dataData)
	customerBiz := biz.NewCustomerBiz()
	customerService := service.NewCustomerService(customerData, customerBiz)
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	httpServer := server.NewHTTPServer(confServer, customerService, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
