// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
<<<<<<< HEAD
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
=======
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
// source: api/verifyCode/verifyCode.proto

package verifyCode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
<<<<<<< HEAD
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerifyCode_GetVerifyCode_FullMethodName = "/api.verifyCode.VerifyCode/GetVerifyCode"
)
=======
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e

// VerifyCodeClient is the client API for VerifyCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifyCodeClient interface {
<<<<<<< HEAD
	// 定义 VerifyCode 服务
=======
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error)
}

type verifyCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyCodeClient(cc grpc.ClientConnInterface) VerifyCodeClient {
	return &verifyCodeClient{cc}
}

func (c *verifyCodeClient) GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error) {
<<<<<<< HEAD
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerifyCodeReply)
	err := c.cc.Invoke(ctx, VerifyCode_GetVerifyCode_FullMethodName, in, out, cOpts...)
=======
	out := new(GetVerifyCodeReply)
	err := c.cc.Invoke(ctx, "/api.verifyCode.VerifyCode/GetVerifyCode", in, out, opts...)
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyCodeServer is the server API for VerifyCode service.
// All implementations must embed UnimplementedVerifyCodeServer
<<<<<<< HEAD
// for forward compatibility.
type VerifyCodeServer interface {
	// 定义 VerifyCode 服务
=======
// for forward compatibility
type VerifyCodeServer interface {
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeReply, error)
	mustEmbedUnimplementedVerifyCodeServer()
}

<<<<<<< HEAD
// UnimplementedVerifyCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifyCodeServer struct{}
=======
// UnimplementedVerifyCodeServer must be embedded to have forward compatible implementations.
type UnimplementedVerifyCodeServer struct {
}
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e

func (UnimplementedVerifyCodeServer) GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifyCode not implemented")
}
func (UnimplementedVerifyCodeServer) mustEmbedUnimplementedVerifyCodeServer() {}
<<<<<<< HEAD
func (UnimplementedVerifyCodeServer) testEmbeddedByValue()                    {}
=======
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e

// UnsafeVerifyCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyCodeServer will
// result in compilation errors.
type UnsafeVerifyCodeServer interface {
	mustEmbedUnimplementedVerifyCodeServer()
}

func RegisterVerifyCodeServer(s grpc.ServiceRegistrar, srv VerifyCodeServer) {
<<<<<<< HEAD
	// If the following call pancis, it indicates UnimplementedVerifyCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
=======
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	s.RegisterService(&VerifyCode_ServiceDesc, srv)
}

func _VerifyCode_GetVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeServer).GetVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
<<<<<<< HEAD
		FullMethod: VerifyCode_GetVerifyCode_FullMethodName,
=======
		FullMethod: "/api.verifyCode.VerifyCode/GetVerifyCode",
>>>>>>> f088d708a9cd6384c0a30c0669e6062431292c3e
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeServer).GetVerifyCode(ctx, req.(*GetVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyCode_ServiceDesc is the grpc.ServiceDesc for VerifyCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.verifyCode.VerifyCode",
	HandlerType: (*VerifyCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerifyCode",
			Handler:    _VerifyCode_GetVerifyCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/verifyCode/verifyCode.proto",
}
